/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanjeewa Kulathunga
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccBalance = new javax.swing.JLabel();
        btnDeleteAcc = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBillPayment = new javax.swing.JButton();
        btnTransferMoney = new javax.swing.JButton();
        lblAltCurrency = new javax.swing.JLabel();
        lblAltBalance = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblAccCurrency = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ewallet");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        lblAccBalance.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lblAccBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccBalance.setText("10000000");
        getContentPane().add(lblAccBalance);
        lblAccBalance.setBounds(140, 320, 240, 50);

        btnDeleteAcc.setBackground(new java.awt.Color(255, 153, 153));
        btnDeleteAcc.setText("Delete Account");
        getContentPane().add(btnDeleteAcc);
        btnDeleteAcc.setBounds(10, 730, 150, 29);

        btnWithdraw.setBackground(new java.awt.Color(102, 255, 102));
        btnWithdraw.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnWithdraw.setText("Withdraw Money");
        getContentPane().add(btnWithdraw);
        btnWithdraw.setBounds(420, 540, 260, 60);

        btnDeposit.setBackground(new java.awt.Color(102, 255, 102));
        btnDeposit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDeposit.setText("Deposit Money");
        getContentPane().add(btnDeposit);
        btnDeposit.setBounds(120, 540, 260, 60);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 730, 110, 29);

        btnBillPayment.setBackground(new java.awt.Color(102, 255, 102));
        btnBillPayment.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBillPayment.setText("Bill Payment");
        getContentPane().add(btnBillPayment);
        btnBillPayment.setBounds(120, 630, 260, 60);

        btnTransferMoney.setBackground(new java.awt.Color(102, 255, 102));
        btnTransferMoney.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnTransferMoney.setText("Tranfer Money");
        btnTransferMoney.setActionCommand("Transfer Money");
        getContentPane().add(btnTransferMoney);
        btnTransferMoney.setBounds(420, 630, 260, 60);

        lblAltCurrency.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAltCurrency.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltCurrency.setText("EUR");
        getContentPane().add(lblAltCurrency);
        lblAltCurrency.setBounds(420, 365, 240, 27);

        lblAltBalance.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lblAltBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltBalance.setText("10000000");
        getContentPane().add(lblAltBalance);
        lblAltBalance.setBounds(420, 320, 240, 50);

        btnLogout.setBackground(new java.awt.Color(255, 255, 153));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(680, 60, 93, 30);

        lblAccCurrency.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAccCurrency.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccCurrency.setText("USD");
        getContentPane().add(lblAccCurrency);
        lblAccCurrency.setBounds(140, 365, 240, 27);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("Sanjeewa Kulathunga");
        lblUserName.setToolTipText("");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(565, 20, 220, 20);

        lblUserEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserEmail.setText("sanjeewakulathunga@hotmail.com");
        lblUserEmail.setToolTipText("");
        getContentPane().add(lblUserEmail);
        lblUserEmail.setBounds(565, 40, 220, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 10, 80, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Layout.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 800);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void addDeleteAccListener(ActionListener listnerforbutton){
        btnDeleteAcc.addActionListener(listnerforbutton);
    }
    public void addLogoutListener(ActionListener listnerforbutton){
        btnLogout.addActionListener(listnerforbutton);
    }
    public void addDepositListener(ActionListener listnerforbutton){
        btnDeposit.addActionListener(listnerforbutton);
    }
    public void addWithdrawListener(ActionListener listnerforbutton){
        btnWithdraw.addActionListener(listnerforbutton);
    }
    public void addBillPaymentListener(ActionListener listnerforbutton){
        btnBillPayment.addActionListener(listnerforbutton);
    }
    public void addTranferListener(ActionListener listnerforbutton){
        btnTransferMoney.addActionListener(listnerforbutton);
    }
    public JLabel getLblUserEmail() {
        return lblUserEmail;
    }

    public void setLblUserEmail(JLabel lblUserEmail) {
        this.lblUserEmail = lblUserEmail;
    }
    
    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public void setBtnLogout(JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    public JLabel getLblUserName() {
        return lblUserName;
    }

    public void setLblUserName(JLabel lblUserName) {
        this.lblUserName = lblUserName;
    }
    
    
    public JButton getBtnBillPayment() {
        return btnBillPayment;
    }

    public void setBtnBillPayment(JButton btnBillPayment) {
        this.btnBillPayment = btnBillPayment;
    }

    public JButton getBtnDeposit() {
        return btnDeposit;
    }

    public void setBtnDeposit(JButton btnDeposit) {
        this.btnDeposit = btnDeposit;
    }

    public JButton getBtnTransferMoney() {
        return btnTransferMoney;
    }

    public void setBtnTransferMoney(JButton btnTransferMoney) {
        this.btnTransferMoney = btnTransferMoney;
    }

    public JButton getBtnWithdraw() {
        return btnWithdraw;
    }

    public void setBtnWithdraw(JButton btnWithdraw) {
        this.btnWithdraw = btnWithdraw;
    }

    public JLabel getLblAccBalance() {
        return lblAccBalance;
    }

    public void setLblAccBalance(JLabel lblAccBalance) {
        this.lblAccBalance = lblAccBalance;
    }

    public JLabel getLblAccCurrency() {
        return lblAccCurrency;
    }

    public void setLblAccCurrency(JLabel lblAccCurrency) {
        this.lblAccCurrency = lblAccCurrency;
    }

    public JLabel getLblAltBalance() {
        return lblAltBalance;
    }

    public void setLblAltBalance(JLabel lblAltBalance) {
        this.lblAltBalance = lblAltBalance;
    }

    public JLabel getLblAltCurrency() {
        return lblAltCurrency;
    }

    public void setLblAltCurrency(JLabel lblAltCurrency) {
        this.lblAltCurrency = lblAltCurrency;
    }
    
    public void DisplayError(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.WARNING_MESSAGE);
    }
    public void DisplayInfo(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.INFORMATION_MESSAGE);
    }
    public int DisplayConfirmDialog(String error){
        return JOptionPane.showConfirmDialog (null,error,"Warning",JOptionPane.YES_NO_OPTION);
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillPayment;
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTransferMoney;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccBalance;
    private javax.swing.JLabel lblAccCurrency;
    private javax.swing.JLabel lblAltBalance;
    private javax.swing.JLabel lblAltCurrency;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
