/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sanjeewa Kulathunga
 */
public class TransactionPanel extends javax.swing.JFrame {

    /**
     * Creates new form TransactionPanel
     */
    public TransactionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txtTo = new javax.swing.JTextField();
        cmbFrom = new javax.swing.JComboBox<>();
        cmbCurrency = new javax.swing.JComboBox<>();
        cmbTo = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 380));
        setMinimumSize(new java.awt.Dimension(640, 380));
        setUndecorated(true);
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("New Transaction: Deposit");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 70, 600, 30);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(580, 20, 40, 40);

        txtTo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(txtTo);
        txtTo.setBounds(260, 220, 280, 30);

        cmbFrom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(cmbFrom);
        cmbFrom.setBounds(260, 140, 280, 31);

        cmbCurrency.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "EUR", "USD" }));
        getContentPane().add(cmbCurrency);
        cmbCurrency.setBounds(180, 310, 140, 31);

        cmbTo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(cmbTo);
        cmbTo.setBounds(260, 220, 280, 31);

        lblTo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTo.setText("To");
        getContentPane().add(lblTo);
        lblTo.setBounds(90, 220, 160, 25);

        btnSubmit.setBackground(new java.awt.Color(102, 255, 102));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(440, 310, 130, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Currency");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 310, 90, 30);

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAmount.setText("Amount");
        getContentPane().add(lblAmount);
        lblAmount.setBounds(90, 180, 160, 27);

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmount);
        txtAmount.setBounds(260, 180, 280, 30);

        lblFrom.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFrom.setText("From Account");
        getContentPane().add(lblFrom);
        lblFrom.setBounds(92, 140, 160, 27);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LayoutTR.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 640, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 380);

        lblType.setText("jLabel2");
        getContentPane().add(lblType);
        lblType.setBounds(30, 30, 51, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    
    public void addTransactionListener(ActionListener listnerforbutton){
        btnSubmit.addActionListener(listnerforbutton);
    }
    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public void setBtnSubmit(JButton btnSubmit) {
        this.btnSubmit = btnSubmit;
    }

    public JComboBox<String> getCmbCurrency() {
        return cmbCurrency;
    }

    public void setCmbCurrency(JComboBox<String> cmbCurrency) {
        this.cmbCurrency = cmbCurrency;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public JTextField getTxtAmount() {
        return txtAmount;
    }

    public void setTxtAmount(JTextField txtAmount) {
        this.txtAmount = txtAmount;
    }

    public JLabel getLblFrom() {
        return lblFrom;
    }

    public void setLblFrom(JLabel lblFrom) {
        this.lblFrom = lblFrom;
    }

    public JComboBox<String> getCmbFrom() {
        return cmbFrom;
    }

    public void setCmbFrom(JComboBox<String> cmbFrom) {
        this.cmbFrom = cmbFrom;
    }

    public JComboBox<String> getCmbTo() {
        return cmbTo;
    }

    public void setCmbTo(JComboBox<String> cmbTo) {
        this.cmbTo = cmbTo;
    }

    public JLabel getLblAmount() {
        return lblAmount;
    }

    public void setLblAmount(JLabel lblAmount) {
        this.lblAmount = lblAmount;
    }

    public JLabel getLblTo() {
        return lblTo;
    }

    public void setLblTo(JLabel lblTo) {
        this.lblTo = lblTo;
    }

    public JLabel getLblType() {
        return lblType;
    }

    public void setLblType(JLabel lblType) {
        this.lblType = lblType;
    }

    public JTextField getTxtTo() {
        return txtTo;
    }

    public void setTxtTo(JTextField txtTo) {
        this.txtTo = txtTo;
    }
    
    public void DisplayError(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.WARNING_MESSAGE);
    }
    public void DisplayInfo(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbCurrency;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
