/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Syed Haseeb
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtFname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        chkFemale = new javax.swing.JRadioButton();
        chkMale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jdcBirthday = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        cmbCurrency = new javax.swing.JComboBox<>();
        cmbMarital = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/CreateAnAccount.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 800, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Your Email ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 120, 40);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtEmail.setToolTipText("");
        txtEmail.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtEmail);
        txtEmail.setBounds(190, 120, 540, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 120, 40);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtPassword);
        txtPassword.setBounds(190, 180, 540, 40);

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtFname.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtFname);
        txtFname.setBounds(190, 240, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 120, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 240, 110, 40);

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtLname.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtLname);
        txtLname.setBounds(500, 240, 230, 40);

        chkFemale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkFemale.setText("Female");
        chkFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(chkFemale);
        chkFemale.setBounds(610, 300, 120, 40);

        chkMale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkMale.setText("Male");
        chkMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaleActionPerformed(evt);
            }
        });
        getContentPane().add(chkMale);
        chkMale.setBounds(510, 300, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Birthday");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 300, 120, 40);

        jdcBirthday.setDateFormatString("yyyy-MM-dd");
        jdcBirthday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jdcBirthday);
        jdcBirthday.setBounds(190, 300, 170, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 300, 110, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 300, 230, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("NIC number");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 360, 120, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setText("City");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 480, 120, 40);

        txtCity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCity.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtCity);
        txtCity.setBounds(190, 480, 540, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Address");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 420, 120, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(750, 10, 40, 40);

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAddress.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtAddress);
        txtAddress.setBounds(190, 420, 540, 40);

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtNIC.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(txtNIC);
        txtNIC.setBounds(190, 360, 170, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Account Currency");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 570, 180, 40);

        btnSubmit.setBackground(new java.awt.Color(102, 255, 153));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSubmit.setText("Create My Account");
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(530, 570, 200, 40);

        cmbCurrency.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR", "USD" }));
        getContentPane().add(cmbCurrency);
        cmbCurrency.setBounds(240, 570, 230, 40);

        cmbMarital.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbMarital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single ", "Married ", "Divorced" }));
        getContentPane().add(cmbMarital);
        cmbMarital.setBounds(500, 360, 230, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("----------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 540, 660, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setText("Marital status");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(370, 360, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 650));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 650));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaleActionPerformed
        if(chkFemale.isSelected()){
            chkFemale.setSelected(false);
        }
    }//GEN-LAST:event_chkMaleActionPerformed

    private void chkFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFemaleActionPerformed
        if(chkMale.isSelected()){
            chkMale.setSelected(false);
        }
    }//GEN-LAST:event_chkFemaleActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    public void addSubmitListener(ActionListener listnerforbutton){
        btnSubmit.addActionListener(listnerforbutton);
    }
    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public void setBtnSubmit(JButton btnSubmit) {
        this.btnSubmit = btnSubmit;
    }

    public JRadioButton getChkFemale() {
        return chkFemale;
    }

    public void setChkFemale(JRadioButton chkFemale) {
        this.chkFemale = chkFemale;
    }

    public JRadioButton getChkMale() {
        return chkMale;
    }

    public void setChkMale(JRadioButton chkMale) {
        this.chkMale = chkMale;
    }

    public JComboBox<String> getCmbCurrency() {
        return cmbCurrency;
    }

    public void setCmbCurrency(JComboBox<String> cmbCurrency) {
        this.cmbCurrency = cmbCurrency;
    }

    public JComboBox<String> getCmbMarital() {
        return cmbMarital;
    }

    public void setCmbMarital(JComboBox<String> cmbMarital) {
        this.cmbMarital = cmbMarital;
    }

    public JDateChooser getJdcBirthday() {
        return jdcBirthday;
    }

    public void setJdcBirthday(JDateChooser jdcBirthday) {
        this.jdcBirthday = jdcBirthday;
    }

    public JTextField getTxtAddress() {
        return txtAddress;
    }

    public void setTxtAddress(JTextField txtAddress) {
        this.txtAddress = txtAddress;
    }

    public JTextField getTxtCity() {
        return txtCity;
    }

    public void setTxtCity(JTextField txtCity) {
        this.txtCity = txtCity;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtFname() {
        return txtFname;
    }

    public void setTxtFname(JTextField txtFname) {
        this.txtFname = txtFname;
    }

    public JTextField getTxtLname() {
        return txtLname;
    }

    public void setTxtLname(JTextField txtLname) {
        this.txtLname = txtLname;
    }

    public JTextField getTxtNIC() {
        return txtNIC;
    }

    public void setTxtNIC(JTextField txtNIC) {
        this.txtNIC = txtNIC;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

     public void DisplayError(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.WARNING_MESSAGE);
    }
    public void DisplayInfo(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton chkFemale;
    private javax.swing.JRadioButton chkMale;
    private javax.swing.JComboBox<String> cmbCurrency;
    private javax.swing.JComboBox<String> cmbMarital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcBirthday;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
